# Full configuration reference available at:
# https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/reference.html
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
            entities:
                App\Entity\Depense: ~
                App\Entity\Alimentation: ~
                App\Entity\User: ~
                App\Entity\Categorie: ~
