knp_paginator:
    page_range: 5                      # Nombre de pages affichées dans la navigation
    default_options:
        page_name: page                # Nom du paramètre de page dans l'URL
        sort_field_name: sort          # Nom du paramètre de tri dans l'URL
        sort_direction_name: direction  # Nom du paramètre de direction dans l'URL
        distinct: true                 # Assure des résultats distincts
        filter_field_name: filterField # Nom du paramètre de filtre dans l'URL
        filter_value_name: filterValue # Nom du paramètre de valeur de filtre dans l'URL
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # Template pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'                # Template pour les liens de tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'                # Template pour les filtres