parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    audit.user.provider:
        class: App\Service\AuditUserProvider
        arguments:
            - '@security.token_storage'
